context:
  initializer:
    classes: com.angorasix.clubs.BeansInitializer
server:
  port: ${PORT:9085}

spring:
  config:
    import: classpath:/wellknownclubs.yml, classpath:/api.yml
  application:
    name: ${APP_NAME:clubs}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/clubs}
