context:
  initializer:
    classes: com.angorasix.clubs.BeansInitializer
server:
  port: ${A6_CLUBS_PORT:9085}

spring:
  config:
    import: classpath:/wellknown.yml, classpath:/api.yml
  application:
    name: ${A6_CLUBS_APP_NAME:clubs}
  data:
    mongodb:
      uri: ${A6_CLUBS_MONGO_DB_URI:mongodb://localhost:27017/clubs}
