context:
  initializer:
    classes: com.angorasix.clubs.BeansInitializer
server:
  port: ${A6_CLUBS_PORT:10900}

logging:
  level:
    root: ${A6_CLUBS_LOGGING_LEVEL_GENERAL:INFO}
    org.springframework.web: ${A6_CLUBS_LOGGING_LEVEL_WEB:INFO}
    com.angorasix: ${A6_CLUBS_LOGGING_LEVEL_ANGORASIX:INFO}

spring:
  config:
    import: optional:file:config/env.properties, classpath:/tokens.yml, classpath:/wellknown.yml, classpath:/api.yml, classpath:/security.yml
  application:
    name: ${A6_CLUBS_APP_NAME:clubs}
  data:
    mongodb:
      uri: ${A6_CLUBS_MONGO_DB_URI:mongodb://localhost:27017/}${A6_CLUBS_MONGO_DB_NAME:a6-clubs}${A6_CLUBS_MONGO_DB_PARAMS:?}
